version: '3.8'

services:
  webapp:
    build: .
    image: spring-boot-webapp:latest
    container_name: spring-boot-webapp
    ports:
      - "8080:8080" 
    depends_on:
      - mongodb
      - redis
    networks:
      - app-network  

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017" 
    environment:
      MONGO_INITDB_DATABASE: test_db
    volumes:
      - mongo-data:/data/db 
    networks:
      - app-network 

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"  
    networks:
      - app-network  

networks:
  app-network:  
    driver: bridge  

volumes:
  mongo-data:  
