version: '3.8'
services:
  app:
    image: demo
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/test_db
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - mongo
      - redis
   networks:
     - backend 

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"  # Exposing MongoDB
    volumes:
      - mongo_data:/data/db
    networks:
     - backend 

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"  # Exposing Redis
    volumes:
      - redis_data:/data
    networks:
     - backend 
     
networks:
  backend:

volumes:
  mongo_data:
  redis_data:
